---

- name: ios config command
  hosts: router


  tasks:
    - name: Execute show command
      ios_interfaces:
        config: 
          - name: interface loopback 1
            description: test for ansible
      
      
#      register: show_output
#
#    - debug:
#        var: show_output
