---

- name: ios config command
  hosts: router


  tasks:
    - name: Execute show command
      ios_command:
        commands:
          - show ip interface brief
      
      register: show_output

    - debug:
        var: show_output