---

- name: ios config command
  hosts: router


  tasks:
    - name: cisco interface configuration
      ios_interfaces:
        config: 
          - name: interface GigabitEthernet 2
            description: test for ansible
            enabled: yes
      
      
#      register: show_output
#
#    - debug:
#        var: show_output
